Jenkinsfile
input/pagecontent/changelog.md
input/pagecontent/search.md
static/BingSiteAuth.xml
static/google745a774a0734f263.html
static/google9d5cd626b0e5379d.html

- google seems to dislike us for some reason

FUT1-14673 changed search to use bing instead of google

---

input/resources/CodeSystem-urn-oid-1.2.208.176.2.4.json
input/resources/ValueSet-ehealth-conditions.json

https://support.systematic.com/browse/FUT1-14616

Added 11 new sks codes

---

.github/workflows/publish.yaml

Read description and authority from sushi-config and hardcode country to dk.

ci: Set missing properties on publish registration

---

input/resources/ValueSet-ehealth-sor-organization-specialty.json

FUT1-15223

---

input/intro-notes/StructureDefinition-ehealth-task-intro.md
input/pagecontent/changelog.md
input/resources/CodeSystem-ehealth-task-handover-roles.json

Added description to task intro page regarding handover 
Added CodeSystem for CareTeams role in handover

FUT1-16621 Added description of handover to Task intro

---

input/resources/CodeSystem-urn-oid-1.2.208.184.100.9.json
input/resources/ValueSet-sundhedsdatastyrelsen-dk-ihe-classcode-vs.json

FUT1-17366 - Corrected display value for code 001 from urn-oid-1.2.208.184.100.9

FUT1-17366 - Corrected display value for code 001

---

input/pagecontent/changelog.md
input/resources/ValueSet-ehealth-conditions.json

FUT1-17679 add sks code to conditions

---

input/intro-notes/StructureDefinition-ehealth-servicerequest-intro.md
input/pagecontent/changelog.md

[Fut1-17663] sekund varighed burde fejle i apply
update description of timing constraints

[Fut1-17663] sekund varighed burde fejle i apply

---

input/fsh/ehealth-questionnaireresponse.fsh
input/intro-notes/StructureDefinition-ehealth-questionnaireresponse-intro.md
input/pagecontent/changelog.md

Added effectivePeriod to QuestionnaireResponse
Updated intro notes for QuestionnaireResponse

CCR0252 questionnaire response effective period

---

input/intro-notes/StructureDefinition-ehealth-actionguidance-intro.md
input/intro-notes/StructureDefinition-ehealth-activitydefinition-intro.md
input/intro-notes/StructureDefinition-ehealth-plandefinition-intro.md
input/intro-notes/StructureDefinition-ehealth-questionnaire-intro.md
input/intro-notes/StructureDefinition-ehealth-view-intro.md
input/pagecontent/changelog.md

ccr0232:
Update IG intro for PlanDefinition, ActivityDefinition, ActionGuidance, View, Questionnaire to state that it is possible to update useContext independent of the status.

Fut1 17709 ccr0232s06 must be possible to change program usecontext independent of the status

---

input/intro-notes/StructureDefinition-ehealth-careteam-intro.md

Added text regarding conditions should be added to reason code and not useContext focus.

[FUT1-17705] FUT1-17705

---

input/pagecontent/changelog.md
input/resources/CodeSystem-ehealth-program.json
input/resources/CodeSystem-ehealth-supplement-hl7-org-fhir-action-selection-behavior.json

Added supplement for action-selection-behavior.
Changed K-PRO to 'Kommunal Pro' for ehealth-program for CCR0232.

FUT1-18777 Add_supplements_and_change_code_for_ehealth_program

---

input/pagecontent/changelog.md
input/resources/OperationDefinition-ehealth-person-match.json

Branched from #92, should be merged (via merge commit) first.

2025.2 CCR236: Update match for historical cpr

---

input/resources/CodeSystem-ehealth-supplement-action-selection-behavior.json

Renamed file as it seems to cause problems with ig build causing NoSuchFileException. also modified a few other properties.

[(Add_supplements_and_change_code_for_ehealth_program)] FUT1-18777

---

.github/pull_request_template.md
README.md
RELEASE.md

🚨 Once this is approved, we should comment on/edit the existing PRs and ensure they target the correct branches.

docs(release): add release process

---

input/intro-notes/StructureDefinition-ehealth-actionguidance-intro.md
input/intro-notes/StructureDefinition-ehealth-activitydefinition-intro.md
input/intro-notes/StructureDefinition-ehealth-plandefinition-intro.md
input/intro-notes/StructureDefinition-ehealth-questionnaire-intro.md
input/intro-notes/StructureDefinition-ehealth-view-intro.md

… ActionGuidance, PlanDefinition, Questionnaire and View

FUT1-18966 expand use context description

---

input/fsh/ehealth-auditevent.fsh
input/pagecontent/changelog.md
input/resources/CodeSystem-audit-restriction-levels.json
input/resources/Valueset-audit-restriction-levels.json

Fut1 19070 ccr0266 s3 add new codings to terminology

---

input/resources/ValueSet-ehealth-device-types.json

Fut1 17026 fix snomed display

---

input/pagecontent/changelog.md

Aligns the content in the IG to the retrofit in the website repo. https://github.com/fut-infrastructure/fut-ig-website/pull/7

125 missing changelog for 351

---

.github/workflows/publish.yaml
check-versions.sh

Ensures the version is correct in `changelog`, `sushi-config` and `publication-request`.

ci: grep for versions before release

---

input/fsh/ehealth-condition.fsh

Fut1 19352

---

input/fsh/ehealth-message.fsh

Fut1 19355

---

input/pagecontent/changelog.md
input/resources/ConceptMap-ehealth.sundhed.dk-ConceptMap-activitydefinition-code-to-observation-code.json

Fut1 12671 update activity def to obs mappings

---

input/fsh/Parameters-expParam.fsh
input/resources/ValueSet-ehealth-message-category.json
input/resources/ValueSet-ehealth-message-medium.json
sushi-config.yaml

Move display and designation to CodeSystems
